# Generated by Django 5.0.2 on 2024-02-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital_Register',
        ),
    ]
