# Generated by Django 5.0.2 on 2024-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
