# Generated by Django 5.0.2 on 2024-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_rename_user_review_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_reviews',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='areas_of_expertise',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
