# Generated by Django 5.0.2 on 2024-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_patient_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='areas_of_expertise',
            field=models.TextField(default=''),
        ),
    ]
